// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_4bAYEsQvR_W0dBbPNKsM_FmIgK5kOao',
    appId: '1:341378575671:web:8a96cfc53ff4de7c1d7eb2',
    messagingSenderId: '341378575671',
    projectId: 'repair-guru-dev',
    authDomain: 'repair-guru-dev.firebaseapp.com',
    storageBucket: 'repair-guru-dev.appspot.com',
    measurementId: 'G-JPNXEP5WRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvmr4LX5KOrXiSKnH2DXWsjM31cnQU2w',
    appId: '1:341378575671:android:d703c2cb1a4ee3031d7eb2',
    messagingSenderId: '341378575671',
    projectId: 'repair-guru-dev',
    storageBucket: 'repair-guru-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhN7qx7qlDJAXBzJCydgw2DNBbASj88PA',
    appId: '1:341378575671:ios:b13f1a4c772905db1d7eb2',
    messagingSenderId: '341378575671',
    projectId: 'repair-guru-dev',
    storageBucket: 'repair-guru-dev.appspot.com',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhN7qx7qlDJAXBzJCydgw2DNBbASj88PA',
    appId: '1:341378575671:ios:e4522fe231cb2b2d1d7eb2',
    messagingSenderId: '341378575671',
    projectId: 'repair-guru-dev',
    storageBucket: 'repair-guru-dev.appspot.com',
    iosBundleId: 'com.example.vendorApp.RunnerTests',
  );
}
